- name: ansible conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 4
  tasks:
  - name: check if number is greater than 5
    ansible.builtin.debug:
      msg: "Number is greater than 5"
    when: NUMBER > 5