- name: ansible conditions
  hosts: local
  connection: local
  vars:
    nginx: true
  tasks:
  - name: check if package is nginx"
    ansible.builtin.yum:
      msg: "Package is nginx"
    when: NAME == "nginx"