- name: ansible conditions
  hosts: local
  connection: local
  become: yes
  vars:
    nginx: true
  tasks:
  - name: check if package is nginx"
    ansible.builtin.yum:
      name: nginx
      state: present
    when: nginx