- name: Print Username and Password
  hosts: local
  connection: local
  vars_prompt:
    - name: Username
      Prompt: Enter your Username
      private: false

    - name: Password
      Prompt: Enter your Password
      private: true

  tasks:
  - name: Print Username and Password
    ansible.builtin.debug:
      msg: "Username: {{ Username }}, Password: {{ Password}}"
