- name : Print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: Username
    prompt: Please enter your username
    private: no
  - name: Password
    prompt: Please enter your password
    private: yes

  tasks:
  - name: Print username and password
    debug:
      msg: "Username: {{ Username}}, Password: {{ Password }}"
      
